from django.urls import path

from .views import (
    comparison_view,
    fines_view,
    index,
    powerbi_data_csv_view,
    powerbi_data_xlsx_view,
    powerbi_uploaded_excel_view,
    powerbi_excel_view,
    powerbi_view,
    powerbi_cook_view,
    powerbi_regression_view,
    powerbi_comparison_view,
    powerbi_comparison_csv_view,
    powerbi_comparison_data_xlsx_view,
    regression_view,
    regression_data_xlsx_view,
    powerbi_fines_view,
    fines_data_xlsx_view,
)

urlpatterns = [
    path("", index, name="index"),
    path("regression/", regression_view, name="regression"),
    path("comparison/", comparison_view, name="comparison"),
    path("fines/", fines_view, name="fines"),
    path("powerbi/", powerbi_view, name="powerbi"),
    path("powerbi/cook/", powerbi_cook_view, name="powerbi_cook"),
    path("powerbi/regression/", powerbi_regression_view, name="powerbi_regression"),
    path("powerbi/comparison/", powerbi_comparison_view, name="powerbi_comparison"),
    path("powerbi/comparison/data.csv", powerbi_comparison_csv_view, name="powerbi_comparison_csv"),
    path("powerbi/comparison/data.xlsx", powerbi_comparison_data_xlsx_view, name="powerbi_comparison_data_xlsx"),
    path("powerbi/excel/", powerbi_excel_view, name="powerbi_excel"),
    path("powerbi/uploaded.xlsx", powerbi_uploaded_excel_view, name="powerbi_uploaded_excel"),
    path("powerbi/data.csv", powerbi_data_csv_view, name="powerbi_data_csv"),
    path("powerbi/data.xlsx", powerbi_data_xlsx_view, name="powerbi_data_xlsx"),
    path("powerbi/fines/", powerbi_fines_view, name="powerbi_fines"),
    path("powerbi/fines/data.xlsx", fines_data_xlsx_view, name="powerbi_fines_data_xlsx"),
    path("regression/data.xlsx", regression_data_xlsx_view, name="regression_data_xlsx"),
]
