# Generated by Django 4.2.30 on 2026-06-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.BinaryField(blank=True, null=True)),
                ('uploaded_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_sheet', models.CharField(blank=True, default='', max_length=255)),
                ('plot_html', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'último estado guardado',
                'verbose_name_plural': 'último estado guardado',
            },
        ),
    ]
