# Generated by Django 4.2.30 on 2026-06-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='plot_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
