# Generated by Django 4.2.30 on 2026-06-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_latestsnapshot_plot_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsnapshot',
            name='plot_html_embed',
            field=models.TextField(blank=True, default=''),
        ),
    ]
